### ISSUE TITLE
Piratenet Example

### ISSUE THREAD

**Issue by Elappnano** [PredictiveIntelligenceLab/jaxpi#15]
Hi, would you release piratenet example for [ns_unsteady_cylinder](https://github.com/PredictiveIntelligenceLab/jaxpi/tree/main/examples/ns_unsteady_cylinder)?

**Comment by Elappnano** [comment]
Yeah, I changed that files, but I think the train file should also change. 
Could you please say which section of the train file should be changed?

**Comment by sifanexisted** [comment]
If you don't use pi_init, you should be good to go.
