### ISSUE TITLE
PIBottleneck error

### ISSUE THREAD

**Issue by Elappnano** [PredictiveIntelligenceLab/jaxpi#16]
what changes need to be made to use PIBottleneck  module. I use it but got bunch of errors. would you publish an example with this module?

**Comment by sifanexisted** [comment]
We use PIResNet in some ablation studies, which can be found [here](https://github.com/PredictiveIntelligenceLab/jaxpi/blob/pirate/examples/grey_scott/gate_sweep.py). This architecture uses PIBottleneck. Please let us know if you encounter any errors. Thank you!
