### ISSUE TITLE
Is this a typo in paper?

### ISSUE THREAD

**Issue by HydrogenSulfate** [PredictiveIntelligenceLab/jaxpi#17]
It seems that the left part of eq 5.6 $K_{bc}$ should be $K_r$, or there will be two same $K_{bc}$...

https://arxiv.org/abs/2308.08468

![image](https://github.com/PredictiveIntelligenceLab/jaxpi/assets/23737287/0435d1b3-195e-4b42-a7c9-e92f6bfa4d3a)

**Comment by sifanexisted** [comment]
Sorry, this is a typo. You are right that it should be $K_r$.
