### ISSUE TITLE
restore checkpoints during training

### ISSUE THREAD

**Issue by Elappnano** [PredictiveIntelligenceLab/jaxpi#21]
Hello
how I should change the training code in order to restore checkpoints?

**Comment by sifanexisted** [comment]
Hello, you could simply use the following code to restore the checkpoints

```
from jaxpi.utils import restore_checkpoint
model.state = restore_checkpoint(model.state, ckpt_path)
```

where ckpt_path is where you save the checkpoints

**Comment by Elappnano** [comment]
thanks, should I replace this line of code in the training loop with the code you suggested?
`model.state = model.step(model.state, batch)`

if not., where I should place that line?

**Comment by Elappnano** [comment]
I got error by resorting checkpoints. could you publish the entire code for the training by using 
`model.state = restore_checkpoint(model.state, ckpt_path)`

**Comment by Elappnano** [comment]
I put the restore code after Initializing the model as follow:

```
model = models.NavierStokes2D(config, inflow_fn, temporal_dom, coords, Re)
ckpt_path = os.path.join(workdir, "/ckpt/", config.wandb.name, "time_window_{}".format(idx + 1))
model.state = restore_checkpoint(model.state, ckpt_path)
```
but got the following error in the train_one_window function:

> ValueError: pmap was requested to map its argument along axis 0, which implies that its rank should be at least 1, but is only 0 (its shape is ())

**Comment by sifanexisted** [comment]
Hello, if you encounter this issue, please add the following line of code  to replicate the state across all devices:

```
state = restore_checkpoint(model.state, ckpt_path)
state = jax_utils.replicate(state)
model.state = state
```

**Comment by Elappnano** [comment]
thanks, I do know in which part of the training code should add these lines. could you elaborate or publish part of the code with these lines.
