### ISSUE TITLE
error in eval code for ns_unsteady_cylinder example

### ISSUE THREAD

**Issue by Elappnano** [PredictiveIntelligenceLab/jaxpi#3]
when I ran the code, the following error appears:

> flax.errors.ScopeParamShapeError: Initializer expected to generate shape (1, 3, 128) but got shape (3, 128) instead for parameter "kernel" in "/FourierEmbs_0". (https://flax.readthedocs.io/en/latest/api_reference/flax.errors.html#flax.errors.ScopeParamShapeError)

**Comment by sifanexisted** [comment]
Do you meet this error when restoring the checkpoint? 

If so, please add `state = jax.device_get(tree_map(lambda x: x[0], model.state))` to extract the first replica of the state.

**Comment by Elappnano** [comment]
No I got this error when run this line

`u_pred = u_pred_fn(params, t_coords, coords[:, 0], coords[:, 1])`

**Comment by Elappnano** [comment]
The error is fixed.
Thats because these lines in the utils.py file of jaxpi folder were commented.
```
    if isinstance(
        jax.tree_map(lambda x: x.sharding, jax.tree_leaves(state.params))[0],
        jax.sharding.PmapSharding,
    ):
        state = jax.tree_map(lambda x: x[0], state)

    # ensuring that we're in a single device setting
    assert isinstance(
        jax.tree_map(lambda x: x.sharding, jax.tree_leaves(state.params))[0],
        jax.sharding.SingleDeviceSharding,
    )
```

**Comment by sifanexisted** [comment]
I commented this out because sometimes the saved parameters are automatically converted to numpy arrays, leading to errors. Either way works.

**Comment by Elappnano** [comment]
so how I should fix the error without uncommenting these lines

**Comment by sifanexisted** [comment]
If you encounter a similar error, consider updating your code like this. The commented-out code performs essentially the same actions but includes a type check:

```
        ckpt_path = os.path.join('.', 'ckpt', config.wandb.name, 'time_window_{}'.format(idx + 1))
        model.state = restore_checkpoint(model.state, ckpt_path)
        model.state = tree_map(lambda x: x[0], model.state)
        params = model.state.params
```

**Comment by Elappnano** [comment]
well. the code goes well for the first time window but for the second I got this error

> IndexError: Too many indices for array: 1 non-None/Ellipsis indices for dim 0.

**Comment by sifanexisted** [comment]
Please go ahead and uncomment the code in `restore_checkpoint`. I apologize for the inconvenience caused. I will work on restoring the commented-out code from the source and ensure to add an additional type check for NumPy arrays

**Comment by Elappnano** [comment]
Ok, Thanks for your support
