### ISSUE TITLE
Is L2error of Allen_cahn's plain config a typo?

### ISSUE THREAD

**Issue by HydrogenSulfate** [PredictiveIntelligenceLab/jaxpi#6]
Jaxpi is a great work for assembling several effective and practical PINN related methods. But according to wandb you given, L2 error of Allen_cahn should be $5.174\times10^{-1}$ rather than $51.74\times 10^{-1}$(that's a really exaggerative error 😲 )?

https://github.com/PredictiveIntelligenceLab/jaxpi/blob/c91a26c0c410553a81690552e1c3d1f04cafea51/examples/allen_cahn/README.md?plain=1#L29
 
![image](https://github.com/PredictiveIntelligenceLab/jaxpi/assets/23737287/2247b212-d97a-40de-93b7-f66c35f17ebd)

**Comment by sifanexisted** [comment]
Thank you for pointing this out! It is a typo and we have fixed it.

**Comment by sifanexisted** [comment]
Thank you for raising this. We apologize for any confusion caused. The correct command to specify different configs is

`python3 main.py --config=configs/sota.py `

**Comment by HydrogenSulfate** [comment]
> Thank you for raising this. We apologize for any confusion caused. The correct command to specify different configs is
> 
> `python3 main.py --config=configs/sota.py `
> 
> By default, it will use `default `config, so users can directly run`python3 main.py`.
> 
> We've included an additional example command to guide users in specifying different configs.

There seems more script to be corrected within 3 example directory: <https://github.com/search?q=repo%3APredictiveIntelligenceLab%2Fjaxpi+%22--config%2F%22&type=code>
